## Este notebook es encargado utilizar el CSV con las prruebas consolidadas para crear y entrenar un modelo

In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import sklearn
from sklearn import preprocessing
import math
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix, roc_auc_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [34]:
biometrics_df = pd.read_csv("./1_standarized_biometrics.csv")
biometrics_df.head()

HR        RR       HRV  MicroSiemens  SCR  SCR_MIN PhaseName  \
0  0.180957 -0.246737 -0.638383      1.604263    0        0     HA_PV   
1  0.463350 -0.508771 -0.930989      1.357679    0        0     HA_PV   
2  0.419905 -0.468458 -1.085573      1.357679    0        0     HA_PV   
3  0.419905 -0.468458 -1.121459      1.111095    0        0     HA_PV   
4  0.506795 -0.549084 -1.088333      1.111095    0        0     HA_PV   

   ArousalMean  Aroused            TimeStamp  ...      HR-2      HR-1  \
0         6.07        1  2020-10-25 19:03:44  ...  0.180957  0.180957   
1         6.07        1  2020-10-25 19:03:44  ...  0.463350  0.463350   
2         6.07        1  2020-10-25 19:03:45  ...  0.419905  0.419905   
3         7.31        1  2020-10-25 19:03:46  ...  0.419905  0.419905   
4         7.31        1  2020-10-25 19:03:46  ...  0.419905  0.419905   

      HRV-4     HRV-3     HRV-2     HRV-1  MicroSiemens-4  MicroSiemens-3  \
0 -0.638383 -0.638383 -0.638383 -0.638383        1.604263        1.604263   
1 -0.930989 -0.930989 -0.930989 -0.930989        1.357679        1.357679   
2 -1.085573 -1.085573 -1.085573 -1.085573        1.357679        1.357679   
3 -1.121459 -1.121459 -1.121459 -1.121459        1.111095        1.111095   
4 -0.638383 -0.930989 -1.085573 -1.121459        1.604263        1.357679   

   MicroSiemens-2  MicroSiemens-1  
0        1.604263        1.604263  
1        1.357679        1.357679  
2        1.357679        1.357679  
3        1.111095        1.111095  
4        1.357679        1.111095  

[5 rows x 22 columns]

In [35]:
# X = biometrics_df[['MicroSiemens', 'HR', 'HRV']].values
X = biometrics_df[['MicroSiemens', 'HR', 'HRV', 'MicroSiemens-4', 'MicroSiemens-3', 'MicroSiemens-2', 'MicroSiemens-1', 'HR-4', 'HR-3', 'HR-2', 'HR-1', 'HRV-4','HRV-3','HRV-2','HRV-1']].values
y = biometrics_df['Aroused'].values

In [36]:
X

array([[ 1.60426292,  0.18095678, -0.63838286, ..., -0.63838286,
        -0.63838286, -0.63838286],
       [ 1.35767905,  0.46335022, -0.93098869, ..., -0.93098869,
        -0.93098869, -0.93098869],
       [ 1.35767905,  0.41990507, -1.08557291, ..., -1.08557291,
        -1.08557291, -1.08557291],
       ...,
       [ 0.92410292, -1.00764835, -1.10377383, ..., -1.0792364 ,
        -1.10868131, -1.12585751],
       [ 1.11904139, -0.46657089, -1.00562414, ..., -1.10868131,
        -1.12585751, -1.10377383],
       [ 1.21651063,  0.73582348, -0.90011322, ..., -1.12585751,
        -1.10377383, -1.00562414]])

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False, random_state=42)

# Models Creation

In [38]:
# model = "adaboost"
model = "knn"
# model = "random-forest"
# model = "svm-rbf"
# model = "svm-poly"

### Adaboost

In [39]:
if model == "adaboost":
    clf = AdaBoostClassifier(n_estimators=100, random_state=42)
    #Adaboost with RandomForest
    clf2 = AdaBoostClassifier(RandomForestClassifier(n_estimators=100), n_estimators=100)
    print(f"Usando {model}")

### KNN

In [40]:
if model == "knn":
    clf = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')

    # Grid Search
    clf.get_params()
    params = {'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}
    grid_search_cv = GridSearchCV(KNeighborsClassifier(), params, n_jobs=-1, verbose=1)
    print(f"Usando {model}")

Usando knn


### Random Forest

In [41]:
if model == "random-forest":
    clf = RandomForestClassifier(random_state=42, n_estimators=100)

    # Grid Search
    rf_clf = RandomForestClassifier(random_state=42, n_estimators=100)
    params_grid = {"max_depth": [3, None], "min_samples_split": [2, 3, 10], "min_samples_leaf": [1, 3, 10], "bootstrap": [True, False], "criterion": ['gini', 'entropy']}
    grid_search_cv = GridSearchCV(rf_clf, params_grid, n_jobs=-1, cv=5, verbose=1, scoring='accuracy', iid=False)
    print(f"Usando {model}")

### SVM rbf

In [42]:
if model == "svm-rbf":
    clf = svm.SVC(C=0.1, gamma=0.01, kernel='rbf')
    
    # Grid Search
    pipeline = Pipeline([('clf', svm.SVC(kernel='rbf', C=1, gamma=0.1))])
    params = {'clf__C':(0.1, 0.5, 1, 2, 5, 10, 20), 'clf__gamma':(0.001, 0.01, 0.1, 0.25, 0.5, 0.75, 1)}
    grid_search_cv = GridSearchCV(pipeline, params, n_jobs=-1, cv=3, verbose=1, scoring='accuracy')
    print(f"Usando {model}")

### SVM Poly

In [43]:
if model == "svm-poly":
    clf = svm.SVC(kernel='poly', degree=3)
    
    # Grid Search
    pipeline = Pipeline([('clf', svm.SVC(kernel='poly'))])
    params = {'clf__C':(0.1, 0.5, 1, 2, 5, 10, 20), 'clf__gamma':(0.001, 0.01, 0.1, 0.25, 0.5, 0.75, 1), 'clf__degree': (3, 4, 5)}
    grid_search_cv = GridSearchCV(pipeline, params, n_jobs=-1, cv=3, verbose=1, scoring='accuracy')
    print(f"Usando {model}")

# Model Fit

In [44]:
clf.fit(X_train, y_train)
grid_search_cv.fit(X_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:    2.1s
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    2.2s finished


GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
             verbose=1)

# Performance Measurement

In [45]:
def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        print("Train Result:\n")
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_train, clf.predict(X_train))))
        print("Accuracy score: {0:.4f}\n".format(accuracy_score(y_train, clf.predict(X_train))))
        print("Classification Report: \n {}\n".format(classification_report(y_train, clf.predict(X_train))))

        res = cross_val_score(clf, X_train, y_train, cv=4, scoring='accuracy')
        print("Cross Validation \t")
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
        
    elif train==False:
        print("Test Result:\n")        
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, clf.predict(X_test))))        
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, clf.predict(X_test))))
        print("Classification Report: \n {}\n".format(classification_report(y_test, clf.predict(X_test))))
        
        res = cross_val_score(clf, X_test, y_test, cv=4, scoring='accuracy')
        print("Cross Validation \t")
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))

## Model performance

In [46]:
print_score(clf, X_train, y_train, X_test, y_test, train=True)
print("\n******************************\n")
print_score(clf, X_train, y_train, X_test, y_test, train=False)

Train Result:

Confusion Matrix: 
 [[548 100]
 [ 88 778]]

Accuracy score: 0.8758

Classification Report: 
               precision    recall  f1-score   support

           0       0.86      0.85      0.85       648
           1       0.89      0.90      0.89       866

    accuracy                           0.88      1514
   macro avg       0.87      0.87      0.87      1514
weighted avg       0.88      0.88      0.88      1514


Cross Validation 	
Average Accuracy: 	 0.6036
Accuracy SD: 		 0.0716

******************************

Test Result:

Confusion Matrix: 
 [[ 72  75]
 [ 87 145]]

accuracy score: 0.5726

Classification Report: 
               precision    recall  f1-score   support

           0       0.45      0.49      0.47       147
           1       0.66      0.62      0.64       232

    accuracy                           0.57       379
   macro avg       0.56      0.56      0.56       379
weighted avg       0.58      0.57      0.58       379


Cross Validation 	
Average 

## Grid Search performance

In [47]:
y_test_pred_grid = grid_search_cv.predict(X_test)

print_score(grid_search_cv, X_train, y_train, X_test, y_test, train=True)
print("\n******************************\n")
print_score(grid_search_cv, X_train, y_train, X_test, y_test, train=False)

grid_search_cv.best_estimator_
grid_search_cv.best_estimator_.get_params()
grid_search_cv.best_params_
grid_search_cv.cv_results_

Train Result:

Confusion Matrix: 
 [[502 146]
 [117 749]]

Accuracy score: 0.8263

Classification Report: 
               precision    recall  f1-score   support

           0       0.81      0.77      0.79       648
           1       0.84      0.86      0.85       866

    accuracy                           0.83      1514
   macro avg       0.82      0.82      0.82      1514
weighted avg       0.83      0.83      0.83      1514


Fitting 5 folds for each of 10 candidates, totalling 50 fits
Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    0.1s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.


Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    0.1s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    0.1s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.


Fitting 5 folds for each of 10 candidates, totalling 50 fits
Cross Validation 	
Average Accuracy: 	 0.6083
Accuracy SD: 		 0.0705

******************************

Test Result:

Confusion Matrix: 
 [[ 71  76]
 [ 89 143]]



[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    0.1s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    0.1s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.


accuracy score: 0.5646

Classification Report: 
               precision    recall  f1-score   support

           0       0.44      0.48      0.46       147
           1       0.65      0.62      0.63       232

    accuracy                           0.56       379
   macro avg       0.55      0.55      0.55       379
weighted avg       0.57      0.56      0.57       379


Fitting 5 folds for each of 10 candidates, totalling 50 fits
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Fitting 5 folds for each of 10 candidates, totalling 50 fits
Cross Validation 	
Average Accuracy: 	 0.6708
Accuracy SD: 		 0.1636


[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    0.1s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  27 out of  50 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    0.1s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:    0.1s finished


{'mean_fit_time': array([0.00200157, 0.00222964, 0.00172729, 0.00176687, 0.0017086 ,
        0.00206332, 0.00279593, 0.00170717, 0.00167432, 0.00172567]),
 'std_fit_time': array([0.00037153, 0.00123755, 0.00020339, 0.00012254, 0.00010024,
        0.00039503, 0.00210512, 0.00011524, 0.00056439, 0.00041793]),
 'mean_score_time': array([0.03607187, 0.04540558, 0.03025632, 0.03425436, 0.03740897,
        0.03978519, 0.03921142, 0.03753319, 0.03596921, 0.02939348]),
 'std_score_time': array([0.0150279 , 0.01890717, 0.00366848, 0.00224634, 0.00422884,
        0.00786763, 0.0041285 , 0.00514302, 0.00295885, 0.00555402]),
 'param_n_neighbors': masked_array(data=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'n_neighbors': 1},
  {'n_neighbors': 2},
  {'n_neighbors': 3},
  {'n_neighbors': 4},
  {'n_neighbors': 5},
  {'n_neighbors': 6},


# Save model to disk

In [48]:
import pickle
# save the model to disk
pickle.dump(grid_search_cv, open('./models/model', 'wb'))
print('Done')

Done
